settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  port: 3000
schema:
- name: headphonista
  path: ./src
  commands:
    install:
      status: true
      method: make build
    build:
      status: true
      method: make build
    run:
      status: true
      method: /go/src/app/src/bin/main
  watcher:
    extensions:
    - go
    - html
    - css
    - js
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
