settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  port: 3000
schema:
- name: headphonista
  path: ./src
  commands:
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
