version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
      - 127.0.0.1:${HTTPS_PORT}:443
    networks:
      headphonista:

  mysqld:
    build:
      context: ./mysql
      dockerfile: Dockerfile.mysql
    ports:
      - 127.0.0.1:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    networks:
      headphonista:

networks:
  headphonista:

