version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/app
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
      - 127.0.0.1:${HTTPS_PORT}:443
      - 127.0.0.1:${REALIZE_PORT}:3000
    command:
      realize start
    depends_on:
      - mysqld
      - ui
    networks:
      headphonista:

  mysqld:
    build:
      context: ./mysql
      dockerfile: Dockerfile.mysql
    ports:
      - 127.0.0.1:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    networks:
      headphonista:

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui
    volumes:
      - ./ui:/go/src/app/ui
    ports:
      - 127.0.0.1:${UI_PORT}:3000
    command: sh -c "yarn install && yarn build && yarn start"
    networks:
      headphonista:

networks:
  headphonista:

